import { useRef, useEffect, useState, lazy, Suspense } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import AnimatedBackground from './AnimatedBackground';
import ParticleCanvas from './ParticleCanvas';
import MorphingLogo from './MorphingLogo';
import HeroContent from './HeroContent';
import ScrollPrompt from './ScrollPrompt';
import CustomCursor from './CustomCursor';
import './Hero.css';

// Lazy load non-critical overlay
const GlitchOverlay = lazy(() => import('./GlitchOverlay'));

gsap.registerPlugin(ScrollTrigger);

const Hero = () => {
    const heroRef = useRef(null);
    const contentRef = useRef(null);
    const [isLoaded, setIsLoaded] = useState(false);

    useEffect(() => {
        // Trigger entrance animation after component mount
        // Small delay to ensure DOM is ready
        const timer = setTimeout(() => setIsLoaded(true), 100);
        return () => clearTimeout(timer);
    }, []);

    useEffect(() => {
        if (!heroRef.current) return;

        // Scroll Destruction Logic
        // Orchestrates the "explosion" of elements as user scrolls down
        const ctx = gsap.context(() => {
            ScrollTrigger.create({
                trigger: heroRef.current,
                start: 'top top',
                end: 'bottom top',
                scrub: 1, // Smooth scrubbing
                onUpdate: (self) => {
                    const progress = self.progress;

                    // 1. Logo spins and shrinks rapidly
                    gsap.to('.morphing-logo', {
                        rotation: progress * 720,
                        scale: Math.max(0, 1 - progress * 2), // Shrinks faster
                        opacity: 1 - progress * 2,
                        overwrite: 'auto'
                    });

                    // 2. Text characters scatter
                    // We target the chars generated by SplitType in HeroContent
                    const chars = document.querySelectorAll('.hero-title .char');
                    chars.forEach((char, i) => {
                        // distinct random angle for each char
                        const angle = (i * 137.5) * (Math.PI / 180); // Golden angle for even scatter
                        const dist = 800 * progress;

                        gsap.to(char, {
                            x: Math.cos(angle) * dist,
                            y: Math.sin(angle) * dist,
                            rotation: 360 * progress * (i % 2 === 0 ? 1 : -1),
                            opacity: 1 - progress,
                            overwrite: 'auto'
                        });
                    });

                    // 3. Subtitle words scatter differently
                    const words = document.querySelectorAll('.hero-subtitle .word');
                    words.forEach((word, i) => {
                        gsap.to(word, {
                            y: 500 * progress,
                            x: (i % 2 === 0 ? -200 : 200) * progress,
                            opacity: 1 - progress * 1.5,
                            overwrite: 'auto'
                        });
                    });

                    // 4. Buttons sink and separate
                    gsap.to('.cta-primary', {
                        x: -100 * progress,
                        y: 200 * progress,
                        opacity: 1 - progress * 3,
                        rotation: -45 * progress,
                        overwrite: 'auto'
                    });
                    gsap.to('.cta-secondary', {
                        x: 100 * progress,
                        y: 200 * progress,
                        opacity: 1 - progress * 3,
                        rotation: 45 * progress,
                        overwrite: 'auto'
                    });
                }
            });
        }, heroRef);

        return () => ctx.revert();
    }, [isLoaded]);

    return (
        <section
            ref={heroRef}
            className="hero-section"
            style={{
                height: '100vh',
                position: 'relative',
                overflow: 'hidden',
                background: '#000000', // Fallback
                cursor: 'none' // Hide default cursor for custom one
            }}
        >
            {/* Layer 1: Animated CSS Gradient Background */}
            <AnimatedBackground />

            {/* Layer 2: Canvas Particle System */}
            <ParticleCanvas />

            {/* Layer 3: SVG Morphing Logo */}
            <MorphingLogo isLoaded={isLoaded} />

            {/* Layer 4: Main Text Content */}
            <HeroContent ref={contentRef} isLoaded={isLoaded} />

            {/* Layer 5: Glitch Overlay */}
            <Suspense fallback={null}>
                <GlitchOverlay />
            </Suspense>

            {/* Layer 6: Custom Cursor */}
            <CustomCursor />

            {/* Scroll Prompt */}
            <ScrollPrompt />
        </section>
    );
};

export default Hero;
